# Permalinks
permalink:           pretty

# Setup
title:               Lucy Allen
tagline:             A Look Into My Life In Data Science
url:                 http://lucy-allen.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lucy Allen
  url:               https://twitter.com/lucy_allenn
  email:             lallen@colgate.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/lucy-allen

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
